name: findin
description: A simple tool to search & replace in files.
version: 0.1.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  ansi: ^0.4.2
  args: ^2.4.2
  duration: ^3.0.13
  intl: ^0.19.0
  meta: ^1.15.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
