name: findin
description: A simple tool to search & replace in files.
version: 0.1.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  freezed_annotation: ^2.4.1
  path: ^1.9.0
  riverpod: ^2.5.1
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  lints: ^3.0.0
  test: ^1.24.0
